version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: coco_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://user:password@db/coco_db
      FLASK_ENV: development  # Включает режим отладки в Flask
    stdin_open: true
    tty: true
    command: ./wait-for-it.sh db:3306 -- python main.py
